apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fanout-target-pubsub
spec:
  type: pubsub.kafka
  metadata:
    - name: brokers
      value: "localhost:9092"
    - name: authRequired
      value: "false"