apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  namespace: hardened
  labels:
    app: app3
    demo: hardened
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
        demo: hardened
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "app3"
        dapr.io/app-protocol: "http"
        dapr.io/app-port: "8083"
        dapr.io/config: "app3-config"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: app
        image: ghcr.io/mchmarny/hardened-app3:v0.1.4
        ports:
        - containerPort: 8083
        env:
        - name: PUBSUB_NAME
          value: "pubsub"
        - name: TOPIC_NAME
          value: "messages"
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: app3-config
  namespace: hardened
spec:
  tracing:
    samplingRate: "1"
  secrets:
    scopes:
      - storeName: kubernetes
        defaultAccess: deny
        allowedSecrets: ["redis-secret"]
          